import os.path

Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui'
]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.StaticLibrary('mo_shared', env.Glob('*.cpp'))

env.AppendUnique(CPPDEFINES = [
    'UNICODE',
    '_UNICODE',
    '_CRT_SECURE_NO_WARNINGS',
    'BOOST_DISABLE_ASSERTS',
    'NDEBUG'
])

env.AppendUnique(CPPPATH = [
    '../bsatk',
    '${BOOSTPATH}',
    '.' # Seriously!
])
