name: Lint ModOrganizer 2

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check format
        uses: ModOrganizer2/check-formatting-action@master
        with:
          check-path: "."
          exclude-regex: "third-party"
